name: market-ms-rubro-dev

services:
  postgres-catalogo-dev:
    image: postgres:16-alpine
    container_name: market-postgres-catalogo-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: market_catalogo_db
      POSTGRES_USER: market
      POSTGRES_PASSWORD: market
    ports:
      - "15432:5432"
    volumes:
      - market_catalogo_dev_data:/var/lib/postgresql/data

volumes:
  market_catalogo_dev_data:
