apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: PostgreSQL Ventas
    uid: postgres-venta
    type: postgres
    access: proxy
    url: host.docker.internal:15434
    user: market
    secureJsonData:
      password: market
    jsonData:
      database: market_orden_db
      sslmode: disable
      postgresVersion: 1500
    editable: true
