name: market-pago-dev

services:
  postgres-pago-dev:
    image: postgres:16-alpine
    container_name: market-postgres-pago-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: market_pago_db
      POSTGRES_USER: market
      POSTGRES_PASSWORD: market
    ports:
      - "15435:5432"
    volumes:
      - market_pago_dev_data:/var/lib/postgresql/data

volumes:
  market_pago_dev_data:
