name: market-cliente-dev

services:
  postgres-cliente-dev:
    image: postgres:16-alpine
    container_name: market-postgres-cliente-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: market_cliente_db
      POSTGRES_USER: market
      POSTGRES_PASSWORD: market
    ports:
      - "15436:5432"
    volumes:
      - market_cliente_dev_data:/var/lib/postgresql/data

volumes:
  market_cliente_dev_data:
