name: market-ms-articulo-dev

services:
  postgres-producto-dev:
    image: postgres:16-alpine
    container_name: market-postgres-producto-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: market_producto_db
      POSTGRES_USER: market
      POSTGRES_PASSWORD: market
    ports:
      - "15433:5432"
    volumes:
      - market_producto_dev_data:/var/lib/postgresql/data

volumes:
  market_producto_dev_data:
